[package]
name = "Rust_Async_Await"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
request = "0.0.8"
tokio = "1.26.0"
